### ISSUE TITLE
运行时问题

### ISSUE THREAD

**Issue by 2177361170** [dk-kling/drivefuzz#1]
你好，我在复现这篇代码时遇到了一些问题，在运行 Behavior Agent时一直提示找不到front.mp4文件，如下图，

![2023-05-09 21-42-04 的屏幕截图](https://github.com/dk-kling/drivefuzz/assets/83916854/1f25475e-19b5-4aee-b213-b123ea72bc73)
请问这这个文件是如何产生的

**Comment by yagol2020** [comment]
hi, @2177361170 , i met same issue, could you please share how to solve this probleam?

**Comment by zhouyu102030** [comment]
hi,@yagol2020 @2177361170 ,I've encountered the same issue as well. Have you resolved it?
