### ISSUE TITLE
code coverage statistics

### ISSUE THREAD

**Issue by aboo18** [dk-kling/drivefuzz#2]
Hello, in studying your code, I found that the code was commented out according to gcc's code coverage statistics, but removing the comments lacks the files such as gcda in the middle of the run, I would like to explore the code coverage issue and would like to ask if there is an existing method in the code, or do I need to rewrite it?

**Comment by dk-kling** [comment]
This repository is just a clone of the following repository. 
For more information, please visit the following gitlab link.

https://gitlab.com/s3lab-code/public/drivefuzz
