### ISSUE TITLE
Showing "Waiting for Autoware nodes" for a long long time

### ISSUE THREAD

**Issue by yagol2020** [dk-kling/drivefuzz#3]
# Desc
Hello, @dk-kling, I've set up the environment for Carla, Autoware, and ROS as per the README instructions. When running DriveFuzz, the terminal displays "**Waiting for Autoware nodes...**" for an extended period of time (I'd say at least 10 minutes or more). It seems like DriveFuzz is stuck. 

Could you please advise on how to resolve this issue?

![image](https://github.com/dk-kling/drivefuzz/assets/67462255/d47fdbda-08e5-480f-bc24-7121b39aa60d)

# Env Info
This is my env:
System: Ubuntu 20.04
GPU: RTX 4080
Mem: 32G
CPU: I7-13700Kf

And, this is `docker ps` when running DriveFuzz
![image](https://github.com/dk-kling/drivefuzz/assets/67462255/3bdddca9-58e2-407e-881e-bb538ba5de4e)

**Comment by dk-kling** [comment]
Hello, @yagol2020.
I'm not an author of DriveFuzz.
You can find [original repository in gitlab](https://gitlab.com/s3lab-code/public/drivefuzz).
